#!/usr/bin/env python3
"""Port the reference's own PDP stylesheet into this theme, renamed but not reinterpreted.

The PDP selector on firstday.com is styled by a single stylesheet the page loads from its CDN:
`/cdn/shop/t/569/assets/PBFCM-PDP-styles.css`. Every earlier attempt at this component measured
the rendered result and wrote CSS to match it, which is slower and strictly worse — a measured
value can be read wrong, and a value that was never measured cannot be reproduced at all.
Porting the source removes both risks: what ships is what the reference ships.

What this changes and why:

- `PBFCM-PDP-<thing>` becomes `lp-buy-box-v2__<thing>`, so the component sits in this theme's
  namespace and cannot collide with anything else on the page.
- `--PBFCM-*` custom properties become `--lp-bbv2-*` for the same reason.
- The result is pretty-printed. The source ships minified, and a 28KB single line is not
  something a person can review or a diff can explain.

What it deliberately does NOT change: any value. No padding is rounded, no colour is snapped to
a token we already had, no breakpoint is normalised — the reference's own 749/751px split is
preserved exactly as authored, gap and all.

Run: python3 tools/port_pdp_styles.py <source.css> > assets/lp-buy-box-v2-ported.css
"""
import re
import sys
from pathlib import Path


def rename(css: str) -> str:
    """Namespace the component without touching any declaration value."""
    css = css.replace("--PBFCM-", "--lp-bbv2-")
    # Longest-first so `product-gallery__main-image` is not eaten by `product-gallery`.
    css = re.sub(r"PBFCM-PDP-([a-zA-Z0-9_-]+)", lambda m: f"lp-buy-box-v2__{m.group(1)}", css)
    # Animation names are global too — two of them would otherwise still read PBFCM.
    css = re.sub(r"PBFCM-(rotate|spin)", lambda m: f"lp-bbv2-{m.group(1)}", css)
    return css


def pretty(css: str) -> str:
    """Expand minified CSS enough to be read and diffed. Not a formatter — just line breaks."""
    out = []
    depth = 0
    token = ""
    for char in css:
        if char == "{":
            selector = " ".join(token.split())
            out.append("  " * depth + selector + " {")
            depth += 1
            token = ""
        elif char == "}":
            if token.strip():
                for decl in (d for d in token.split(";") if d.strip()):
                    out.append("  " * depth + " ".join(decl.split()) + ";")
            depth = max(0, depth - 1)
            out.append("  " * depth + "}")
            token = ""
        elif char == ";" and depth > 0:
            if token.strip():
                out.append("  " * depth + " ".join(token.split()) + ";")
            token = ""
        else:
            token += char
    return "\n".join(out) + "\n"


HEADER = """/* PDP selector styles, ported from the reference's own stylesheet.
 *
 * Source: firstday.com/cdn/shop/t/569/assets/PBFCM-PDP-styles.css
 * Generated by tools/port_pdp_styles.py — edit that, or the source, not this file.
 *
 * Only two things were changed: `PBFCM-PDP-*` class names became `lp-buy-box-v2__*` and
 * `--PBFCM-*` properties became `--lp-bbv2-*`, both so the component sits in this theme's
 * namespace. Every value is the reference's own, unrounded and unreinterpreted, including its
 * 749/751px breakpoint gap.
 *
 * Measuring the rendered component and writing CSS to match it — which is what the earlier
 * passes did — can only ever approximate this, and can only reproduce what someone thought to
 * measure. Porting the source reproduces what the reference actually does, including the parts
 * nobody thought to look at.
 */

"""


def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "PBFCM-PDP-styles.css")
    css = src.read_text(encoding="utf-8")
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    sys.stdout.write(HEADER + pretty(rename(css)))


if __name__ == "__main__":
    main()
