#!/usr/bin/env python3
"""Extract a component's real CSS out of the reference snapshot so it can be applied directly.

The reference styles most of this page from inline <style> blocks and a handful of CDN
stylesheets. Every pass at fidelity before this one measured the rendered result and wrote CSS
to match it, which is slower and strictly worse in two ways: a measured value can be read
wrong, and a value nobody thought to measure cannot be reproduced at all. The PDP selector
proved the alternative — port the source and the component matches by construction.

This does the same for the rest of the page. It pulls every rule whose selector mentions a
given class prefix, out of both the inline blocks and any linked stylesheet already saved
alongside, and rewrites the prefix into this theme's namespace.

The point of the namespace is that our markup then carries BOTH class names: its own, which the
JS and the schema use, and the reference's, which this CSS targets. Nothing is translated, so
nothing can drift in translation — the rule that styles our element is the rule that styles
theirs, character for character.

What it never does is change a value. No padding is rounded, no colour is snapped to a token
we already have, no breakpoint is normalised.

Run: python3 tools/port_reference_styles.py <prefix> [more prefixes...]
     e.g. python3 tools/port_reference_styles.py science-tabs accordion-block
"""
import re
import sys
from pathlib import Path

SNAPSHOT = Path("/home/lcam/firstday-assignment/inputs/fd-lp.html")
NAMESPACE = "lpref-"


def blocks(html: str):
    """Inline <style> bodies, in document order — order is part of the cascade."""
    return re.findall(r"<style[^>]*>(.*?)</style>", html, re.S)


def split_rules(css: str):
    """Yield (selector, body) pairs, keeping @media wrappers intact around their contents."""
    out, depth, buf = [], 0, ""
    for char in css:
        buf += char
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                out.append(buf.strip())
                buf = ""
    return out


def mentions(rule: str, prefixes) -> bool:
    head = rule.split("{", 1)[0]
    return any(f".{p}" in head for p in prefixes)


def harvest(css: str, prefixes):
    """Rules matching the prefixes, including those nested inside @media."""
    kept = []
    for rule in split_rules(css):
        head = rule.split("{", 1)[0].strip()
        if head.startswith("@media") or head.startswith("@supports"):
            inner = rule[rule.index("{") + 1: rule.rindex("}")]
            nested = [r for r in split_rules(inner) if mentions(r, prefixes)]
            if nested:
                kept.append(head + " {\n" + "\n".join("  " + n for n in nested) + "\n}")
        elif mentions(rule, prefixes):
            kept.append(rule)
    return kept


def namespace(css: str, prefixes) -> str:
    for p in sorted(prefixes, key=len, reverse=True):
        css = re.sub(rf"\.{re.escape(p)}", f".{NAMESPACE}{p}", css)
    return css


def main() -> None:
    prefixes = sys.argv[1:]
    if not prefixes:
        print(__doc__)
        raise SystemExit(2)

    html = SNAPSHOT.read_text(encoding="utf-8", errors="replace")
    rules = []
    for body in blocks(html):
        rules.extend(harvest(body, prefixes))

    header = (
        "/* Ported verbatim from the reference's own stylesheets.\n"
        f" * Prefixes: {', '.join(prefixes)}\n"
        " * Generated by tools/port_reference_styles.py — regenerate, do not hand-edit.\n"
        " *\n"
        " * Only the class prefix changed, so our markup can carry the reference's class names\n"
        " * alongside its own and be styled by the reference's own rules. No value was touched:\n"
        " * nothing rounded, nothing re-tokenised, no breakpoint normalised.\n"
        " */\n\n"
    )
    print(header + namespace("\n\n".join(rules), prefixes))
    print(f"/* {len(rules)} rules */", file=sys.stderr)


if __name__ == "__main__":
    main()
